# ======================
# H2 DATABASE CONFIG 
# ======================
#spring.datasource.url=jdbc:h2:mem:testdb //temporary in RAM data stored
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.username=sa
spring.datasource.password=

# ======================
# JPA CONFIG
# ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ======================
# H2 CONSOLE temporarily commented to avoid conflict with AWS-RDS.
# ======================
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Swagger UI access -- http://localhost:8080/swagger-ui 
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui

# ===================
#AWS 
# dbpwd:Aws_Learning_Spring
# instance dbName- Java-SpringBoot-Node-React-employee-db

#==================
spring.datasource.url=jdbc:postgresql://java-springboot-node-react-employee-db.c0lesey8ch1x.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Aws_Learning_Spring
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Tokens - using free jwt secret key generator base64
jwt.secret=O9xxMcV8iyPCSuw6OCdi5rzUD3YmppEMHoOjYI9lEhR
jwt.expiration=3600000

#server.port=8081