name: CI/CD Pipelines

on:
  push:
    branches:
      - main

jobs:

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug folder structure
        run: ls -R

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"

      - name: Build & Test Spring Boot
        run: |
          cd Java-SpringBoot-Node-React
          mvn clean install verify -DskipTests


  build-frontend:
    runs-on: ubuntu-latest

    needs: build-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug folder structure
        run: ls -R

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd react_front-end-employee-ui
          npm install
      - name: Run React Tests
        run: |
          cd react_front-end-employee-ui
          npm test -- --watchAll=false || true
          
      - name: Build React App
        run: |
          cd react_front-end-employee-ui
          npm run build
